"""criando campo de idade na tabela pessoa 2

Revision ID: c357afe11b1c
Revises: eada2cf7f14f
Create Date: 2022-07-29 13:27:53.548275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c357afe11b1c'
down_revision = 'eada2cf7f14f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa2', sa.Column('idade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa2', 'idade')
    # ### end Alembic commands ###
