"""criando campo de senha na tabela pessoa

Revision ID: e6a1748a3b5a
Revises: eb3840cf7e7b
Create Date: 2022-07-29 13:15:49.504525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a1748a3b5a'
down_revision = 'eb3840cf7e7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('senha', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###
    # pessoas = sa.select('pessoa')
    # for pessoa in pessoas:
    #     pessoa.senha = 'senha@123'
    #     pessoa.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa', 'senha')
    # ### end Alembic commands ###
